name: offline_sync
description: On-device RAG with Flutter Gemma
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  crypto: ^3.0.7
  device_info_plus: ^12.3.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_gemma: ^0.12.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get_it: ^8.3.0
  injectable: ^2.5.0
  intl: ^0.20.2
  logger: any
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqlite3: ^3.1.3
  sqlite3_flutter_libs: ^0.5.24
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  stacked_shared: any
  system_info_plus: ^0.0.6
  url_launcher: ^6.3.2
dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.12.0
  mocktail: ^1.0.4
  path_provider_platform_interface: any
  very_good_analysis: ^10.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/models/
