name: offline_sync
description: On-device RAG with Flutter Gemma
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  animations: ^2.1.1
  archive: ^4.0.7
  crypto: ^3.0.7
  device_info_plus: ^12.3.0
  epub_plus: ^5.1.0
  file_picker: ^10.3.8
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_gemma: ^0.12.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get_it: ^8.3.0
  google_fonts: ^7.0.2
  intl: ^0.20.2
  logger: any
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqlite3: ^3.1.3
  sqlite3_flutter_libs: ^0.5.24
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  stacked_shared: any
  syncfusion_flutter_pdf: ^32.1.23
  system_info_plus: ^0.0.6
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  xml: ^6.6.1
dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path_provider_platform_interface: any
  stacked_generator: ^2.0.0
  very_good_analysis: ^10.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/models/
