name: offline_sync
description: An Offline-first RAG app with data sync
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.12.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  stacked: ^3.5.0
  stacked_services: ^1.6.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  stacked_generator:
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
